"""empty message

Revision ID: a962177d99a0
Revises: 
Create Date: 2020-01-17 12:44:03.989505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a962177d99a0'
down_revision = None
branch_labels = None
depends_on = None


def seed():
    member_table = sa.sql.table(
        'member',
        sa.sql.column('first_name', sa.String),
        sa.sql.column('last_name', sa.String)
    )

    op.bulk_insert(
        member_table,
        [
            {'id': 1, 'first_name': 'Erin', 'last_name': 'Stuelke'},
            {'id': 2, 'first_name': 'Shawn', 'last_name': 'Suter'},
            {'id': 3, 'first_name': 'Betsy', 'last_name': 'Carretta'},
            {'first_name': 'Bob', 'last_name': 'Ross'}
        ]
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailchimp_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('list_type', sa.String(length=30), nullable=True),
    sa.Column('mailchimp_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mailchimp_tag_id'], ['mailchimp_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    seed()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_membership')
    op.drop_table('list')
    op.drop_table('member')
    op.drop_table('mailchimp_tag')
    # ### end Alembic commands ###
