"""empty message

Revision ID: b8cde0b43c16
Revises: 
Create Date: 2020-01-24 17:17:58.421159

"""
from alembic import op
import sqlalchemy as sa
from backend.helpers.import_seed_data import seed_data


# revision identifiers, used by Alembic.
revision = 'b8cde0b43c16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('list_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=False),
    sa.Column('is_executive_assistant', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('executive_assistant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['executive_assistant_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_memberships',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], )
    )
    op.create_table('phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cure_center_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=30), nullable=True),
    sa.Column('suffix', sa.String(length=30), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('is_qura_funded', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=120), nullable=True),
    sa.Column('onyen', sa.String(length=30), nullable=True),
    sa.Column('staff_designation', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['cure_center_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    seed_data()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('cure_center_profile')
    op.drop_table('phone_number')
    op.drop_table('list_memberships')
    op.drop_table('group')
    op.drop_table('email')
    op.drop_table('member')
    op.drop_table('list')
    # ### end Alembic commands ###
